# Generated by Django 5.0.2 on 2024-03-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_image1_customuser_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image1',
            field=models.ImageField(default=' ', upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image2',
            field=models.ImageField(default=' ', upload_to='pics'),
        ),
    ]
