# Generated by Django 5.0.1 on 2024-03-14 14:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(default=' ', max_length=30, unique=True)),
                ('image1', models.ImageField(upload_to='pics')),
                ('image2', models.ImageField(upload_to='pics')),
                ('desc', models.TextField()),
                ('email', models.EmailField(max_length=100)),
                ('degree', models.TextField(max_length=100)),
                ('job_role', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
