# Generated by Django 5.0.1 on 2024-03-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('image1', models.ImageField(upload_to='pics')),
                ('image2', models.ImageField(upload_to='pics')),
                ('mail', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('degree', models.TextField(max_length=100)),
                ('job_role', models.CharField(max_length=100)),
            ],
        ),
    ]
